Repository In-lyeog-sa-mu-so/jjoin-server, pull requests merged in 2023-09, with the labels that each got.

#6 ✨ Feat: 엔티티 생성 Part2 (Group, Recruited, User Entity 수정)
  src/main/java/org/dongguk/jjoin/domain/Group.java
  src/main/java/org/dongguk/jjoin/domain/Group_application.java
  src/main/java/org/dongguk/jjoin/domain/Group_member.java
  src/main/java/org/dongguk/jjoin/domain/Group_tag.java
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
  src/main/java/org/dongguk/jjoin/domain/Tag.java
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/java/org/dongguk/jjoin/domain/type/DependentType.java
  src/main/java/org/dongguk/jjoin/domain/type/ELoginProvider.java
  src/main/java/org/dongguk/jjoin/domain/type/EUserRole.java
  src/main/java/org/dongguk/jjoin/domain/type/RankType.java
Labels: FEAT

#7 ✨ Feat: 엔티티 생성 Part1
  src/main/java/org/dongguk/jjoin/domain/Album.java
  src/main/java/org/dongguk/jjoin/domain/Enrollment.java
  src/main/java/org/dongguk/jjoin/domain/Event.java
  src/main/java/org/dongguk/jjoin/domain/GroupDeletion.java
  src/main/java/org/dongguk/jjoin/domain/Image.java
  src/main/java/org/dongguk/jjoin/domain/Notice.java
  src/main/java/org/dongguk/jjoin/domain/Schedule.java
  src/main/java/org/dongguk/jjoin/domain/type/ImageType.java
Labels: FEAT, 선호

#10 🎨 Refactor: Entity Part1,2 연결 및 연관관계 설정
  src/main/java/org/dongguk/jjoin/domain/Album.java
  src/main/java/org/dongguk/jjoin/domain/Enrollment.java
  src/main/java/org/dongguk/jjoin/domain/Event.java
  src/main/java/org/dongguk/jjoin/domain/Group.java
  src/main/java/org/dongguk/jjoin/domain/GroupApplication.java
  src/main/java/org/dongguk/jjoin/domain/GroupMember.java
  src/main/java/org/dongguk/jjoin/domain/GroupTag.java
  src/main/java/org/dongguk/jjoin/domain/Notice.java
  src/main/java/org/dongguk/jjoin/domain/Tag.java
  src/main/java/org/dongguk/jjoin/domain/User.java
Labels: 재형, REFACTOR

#11 🎨 Refactor: Entity 예약어 수정 및 로컬 db연동 설정 추가
  src/main/java/org/dongguk/jjoin/domain/Album.java
  src/main/java/org/dongguk/jjoin/domain/Club.java
  src/main/java/org/dongguk/jjoin/domain/ClubApplication.java
  src/main/java/org/dongguk/jjoin/domain/ClubDeletion.java
  src/main/java/org/dongguk/jjoin/domain/ClubMember.java
  src/main/java/org/dongguk/jjoin/domain/ClubTag.java
  src/main/java/org/dongguk/jjoin/domain/Enrollment.java
  src/main/java/org/dongguk/jjoin/domain/Image.java
  src/main/java/org/dongguk/jjoin/domain/Notice.java
  src/main/java/org/dongguk/jjoin/domain/Plans.java
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
  src/main/java/org/dongguk/jjoin/domain/Schedule.java
  src/main/java/org/dongguk/jjoin/domain/Tag.java
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/resources/application.properties
Labels: 선호, REFACTOR

#13 🎨 Refactor: Entity 컬럼명 및 클래스 명 수정
  src/main/java/org/dongguk/jjoin/domain/Club.java
  src/main/java/org/dongguk/jjoin/domain/ClubApplication.java
  src/main/java/org/dongguk/jjoin/domain/ClubDeletion.java
  src/main/java/org/dongguk/jjoin/domain/ClubMember.java
  src/main/java/org/dongguk/jjoin/domain/ClubTag.java
  src/main/java/org/dongguk/jjoin/domain/Plan.java
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
  src/main/java/org/dongguk/jjoin/domain/Schedule.java
  src/main/java/org/dongguk/jjoin/domain/User.java
Labels: 선호, REFACTOR

#20 ✨ Feat: 일정 API 구현
  src/main/java/org/dongguk/jjoin/controller/ScheduleController.java
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
  src/main/java/org/dongguk/jjoin/domain/Schedule.java
  src/main/java/org/dongguk/jjoin/dto/response/ResponseDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ScheduleDayDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ScheduleDaysDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
  src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java
  src/main/java/org/dongguk/jjoin/repository/UserRepository.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
  src/main/java/org/dongguk/jjoin/util/DateUtil.java
Labels: FEAT, 선호

#24 ✨ Feat: 동아리 게시글 구현 (앱)
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/dto/response/NoticeListDtoByApp.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
Labels: FEAT, 재형

#25 🐛 Fix: showNoticeList 수정
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: 재형, FIX
