Repository In-lyeog-sa-mu-so/jjoin-server, pull requests merged in 2023-10, with the labels that each got.

#27 Feat/home api
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/controller/ScheduleController.java
  src/main/java/org/dongguk/jjoin/controller/UserController.java
  src/main/java/org/dongguk/jjoin/dto/request/ScheduleDecideDto.java
  src/main/java/org/dongguk/jjoin/dto/request/UserTagDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubCardDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubRecommendDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
  src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
  src/main/java/org/dongguk/jjoin/repository/ClubTagRepository.java
  src/main/java/org/dongguk/jjoin/repository/NoticeRepository.java
  src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java
  src/main/java/org/dongguk/jjoin/repository/UserRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
  src/main/java/org/dongguk/jjoin/service/UserService.java
Labels: FEAT, 선호

#31 ✨ Feat : 동아리 검색 API 구현
  src/main/java/org/dongguk/jjoin/controller/SearchController.java
  src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
  src/main/java/org/dongguk/jjoin/repository/ClubTagRepository.java
  src/main/java/org/dongguk/jjoin/repository/TagRepository.java
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: FEAT, 재형

#34 ✨ Feat : App - 일정 상세 및 사진첩 상세 API 구현
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubAlbumDetailDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDetailDto.java
  src/main/java/org/dongguk/jjoin/service/AlbumService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
Labels: FEAT, 선호

#36 🐛 Fix: User table의 학과 column 추가
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/java/org/dongguk/jjoin/domain/type/MajorType.java
Labels: 재형, FIX

#40 ✨ Feat : Web - 동아리 멤버 관리 API 구현
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/domain/ClubMember.java
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubMemberDtoByWeb.java
  src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: FEAT, 재형

#41 ✨ Feat : App - 마이페이지 API 구현
  src/main/java/org/dongguk/jjoin/controller/UserController.java
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/java/org/dongguk/jjoin/dto/request/UserProfileUpdateDto.java
  src/main/java/org/dongguk/jjoin/dto/response/UserClubDto.java
  src/main/java/org/dongguk/jjoin/dto/response/UserProfileDto.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/UserService.java
Labels: FEAT, 선호

#45 ✨ Feat : Web - 동아리 메인페이지 API 구현
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
  src/main/java/org/dongguk/jjoin/dto/ClubMemberDtoByWeb.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageDtoByWeb.java
  src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
  src/main/java/org/dongguk/jjoin/repository/ImageRepository.java
  src/main/java/org/dongguk/jjoin/repository/RecruitedPeriodRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: FEAT, 재형

#46 ✨ Feat : App - 일정 API 구현
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/domain/Plan.java
  src/main/java/org/dongguk/jjoin/dto/request/PlanRequestDto.java
  src/main/java/org/dongguk/jjoin/dto/request/PlanUpdateDto.java
  src/main/java/org/dongguk/jjoin/dto/response/PlanDto.java
  src/main/java/org/dongguk/jjoin/service/PlanService.java
Labels: FEAT, 선호
