Repository In-lyeog-sa-mu-so/jjoin-server, pull requests merged in 2023-11, with the labels that each got.

#47 ✨ Feat : Web - 일정 API 구현
  src/main/java/org/dongguk/jjoin/controller/AdminController.java
  src/main/java/org/dongguk/jjoin/domain/Club.java
  src/main/java/org/dongguk/jjoin/domain/Enrollment.java
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/java/org/dongguk/jjoin/dto/request/EnrollmentUpdateDto.java
  src/main/java/org/dongguk/jjoin/dto/response/EnrollmentDto.java
  src/main/java/org/dongguk/jjoin/repository/EnrollmentRepository.java
  src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
Labels: FEAT, 선호

#50 ✨ Feat : Web - 동아리 삭제 API 구현
  src/main/java/org/dongguk/jjoin/controller/AdminController.java
  src/main/java/org/dongguk/jjoin/domain/ClubDeletion.java
  src/main/java/org/dongguk/jjoin/dto/request/ClubDeletionUpdateDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubDeletionDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubDeletionRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubDeletionService.java
Labels: FEAT, 선호

#51 ✨ Feat : Web - 동아리 지원서 관련 Table 추가
  src/main/java/org/dongguk/jjoin/domain/Application_answer.java
  src/main/java/org/dongguk/jjoin/domain/Application_question.java
  src/main/java/org/dongguk/jjoin/domain/Club.java
  src/main/java/org/dongguk/jjoin/domain/ClubApplication.java
Labels: FEAT, 재형

#52 ✨ Feat : Web - 동아리 개설 신청 API 구현
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/domain/Club.java
  src/main/java/org/dongguk/jjoin/domain/type/DependentType.java
  src/main/java/org/dongguk/jjoin/dto/request/ClubEnrollmentRequestDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentResponseDto.java
  src/main/java/org/dongguk/jjoin/repository/EnrollmentRepository.java
  src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
Labels: FEAT, 선호

#54 ✨ Feat : Web - 동아리 가입 신청 API 구현
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/domain/Application_answer.java
  src/main/java/org/dongguk/jjoin/domain/Application_question.java
  src/main/java/org/dongguk/jjoin/dto/request/ApplicationQuestionDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationDetailDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationQAset.java
  src/main/java/org/dongguk/jjoin/repository/AnswerRepository.java
  src/main/java/org/dongguk/jjoin/repository/ApplicationRepository.java
  src/main/java/org/dongguk/jjoin/repository/QuestionRepository.java
  src/main/java/org/dongguk/jjoin/repository/UserRepository.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: FEAT, 재형

#58 ✨ Feat: App - 동아리 가입신청서 API 구현
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/dto/request/ApplicationAnswerDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationFormDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationQuestionDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
  src/main/java/org/dongguk/jjoin/repository/QuestionRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
Labels: FEAT, 재형

#62 ✨ Feat: Web - 관리자가 관리하는 동아리 조회 API 구현
  src/main/java/org/dongguk/jjoin/controller/AdminController.java
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentResponseDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ManagingClubDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
  src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: FEAT, 재형

#63 🐛 Fix: ClubController 버그 수정
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/java/org/dongguk/jjoin/dto/request/UserTagDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubDetailDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageDtoByWeb.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubRecommendDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDetailDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDto.java
  src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubTagRepository.java
  src/main/java/org/dongguk/jjoin/repository/PlanRepository.java
  src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
  src/main/java/org/dongguk/jjoin/service/PlanService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: 선호, FIX

#66 ✨ Feat: App - 동아리 태그 목록 조회 API 구현
  src/main/java/org/dongguk/jjoin/controller/SearchController.java
  src/main/java/org/dongguk/jjoin/dto/response/TagDto.java
  src/main/java/org/dongguk/jjoin/repository/TagRepository.java
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: FEAT, 재형

#68 ✨ Feat : 동아리 일정 조회 기능 추가 및 기존 일정 조회 기능 수정
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/controller/ScheduleController.java
  src/main/java/org/dongguk/jjoin/controller/UserController.java
  src/main/java/org/dongguk/jjoin/domain/Schedule.java
  src/main/java/org/dongguk/jjoin/dto/request/PlanRequestDto.java
  src/main/java/org/dongguk/jjoin/dto/request/PlanUpdateDto.java
  src/main/java/org/dongguk/jjoin/dto/request/ScheduleDecideDto.java
  src/main/java/org/dongguk/jjoin/dto/response/PlanDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ScheduleDayDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ScheduleDaysDto.java
  src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
  src/main/java/org/dongguk/jjoin/repository/PlanRepository.java
  src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java
  src/main/java/org/dongguk/jjoin/service/PlanService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
  src/main/java/org/dongguk/jjoin/util/DateUtil.java
Labels: FEAT, 선호

#70 ✨ Feat : 일정 조회 페이징 기능 추가 및 프로퍼티 수정
  src/main/java/org/dongguk/jjoin/repository/PlanRepository.java
  src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
  src/main/resources/application.properties
Labels: FEAT, 선호

#75 🐛 FIX: API 명세에 맞게 응답Dto 프로퍼티명 수정
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/controller/SearchController.java
Labels: 재형, FIX

#73 🐛 Fix: 마이페이지 및 동아리 조회, 개설신청서 CRUD 수정
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/controller/UserController.java
  src/main/java/org/dongguk/jjoin/dto/request/ClubEnrollmentRequestDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubCardDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentResponseDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDetailDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ScheduleDayDto.java
  src/main/java/org/dongguk/jjoin/dto/response/UserClubDto.java
  src/main/java/org/dongguk/jjoin/dto/response/UserProfileDto.java
  src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
  src/main/java/org/dongguk/jjoin/service/UserService.java
Labels: 선호, FIX

#77 🐛 FIX: App - 동아리 검색시 응답값 LeaderName 추가
  src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: 재형, FIX

#78 🐛 FIX: App 동아리 가입신청서 목록,상세 조회시 Id값 추가
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationDto.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: 재형, FIX

#81 🐛 Fix: 동아리 모집기관 완료 Boolean 속성 추가
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubDetailDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageDtoByWeb.java
  src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: 선호, FIX

#83 🐛 Fix: 배열 data 매핑 추가
  src/main/java/org/dongguk/jjoin/controller/AdminController.java
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/controller/ScheduleController.java
  src/main/java/org/dongguk/jjoin/controller/SearchController.java
  src/main/java/org/dongguk/jjoin/controller/UserController.java
Labels: 선호, FIX

#86 ✨ Feat : 하루 일정 반환 수정 및 사용자 학번 정보 추가
  src/main/java/org/dongguk/jjoin/dto/response/UserProfileDto.java
  src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
  src/main/java/org/dongguk/jjoin/service/UserService.java
Labels: FEAT, 선호

#87 🐛 Fix : Web - 가입신청서 질문 생성 엔드포인트, 쿼리메소드 Param 추가
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/repository/AnswerRepository.java
  src/main/java/org/dongguk/jjoin/repository/ApplicationRepository.java
  src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
  src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
  src/main/java/org/dongguk/jjoin/repository/TagRepository.java
Labels: 재형, FIX

#88 ✨ Feat: Web - 가입 신청서 질문 관련 API 구현
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/domain/Application_question.java
  src/main/java/org/dongguk/jjoin/dto/request/QuestionDeleteDto.java
  src/main/java/org/dongguk/jjoin/dto/request/QuestionModifyDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationFormDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ApplicationQuestionResponseDto.java
  src/main/java/org/dongguk/jjoin/repository/QuestionRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: FEAT, 재형

#92 🐛 Fix : ResponseDto에 페이지네이션 정보 추가
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/controller/SearchController.java
  src/main/java/org/dongguk/jjoin/dto/page/ApplicationPageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/ClubMemberPageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/NoticeAppPageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/NoticeWebPageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/PageInfo.java
  src/main/java/org/dongguk/jjoin/dto/page/SearchClubPageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/TagPageDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubMemberDto.java
  src/main/java/org/dongguk/jjoin/repository/ApplicationRepository.java
  src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
  src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
  src/main/java/org/dongguk/jjoin/repository/NoticeRepository.java
  src/main/java/org/dongguk/jjoin/repository/TagRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: 재형, FIX

#94 🐛 Fix : 동아리 멤버 조회시 email 값 추가해서 반환
  src/main/java/org/dongguk/jjoin/dto/response/ClubMemberDto.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: 재형, FIX

#96 ✨ Feat: Web - 동아리 관리자 페이지 정보 추가 및 pageInfo 추가
  src/main/java/org/dongguk/jjoin/controller/AdminController.java
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/controller/ManagerController.java
  src/main/java/org/dongguk/jjoin/dto/page/ClubDeletionPageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/ClubEnrollmentPageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/ClubSchedulePageDto.java
  src/main/java/org/dongguk/jjoin/dto/page/EnrollmentPageDto.java
  src/main/java/org/dongguk/jjoin/dto/response/ManagingClubDto.java
  src/main/java/org/dongguk/jjoin/repository/EnrollmentRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubDeletionService.java
  src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
Labels: FEAT, 선호

#99 🐛 FIX: Web - 게시글 번호 꼬임 문제 해결
  src/main/java/org/dongguk/jjoin/controller/ClubController.java
  src/main/java/org/dongguk/jjoin/dto/response/NoticeListDto.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
  src/main/java/org/dongguk/jjoin/service/ScheduleService.java
Labels: FEAT, 선호

#101 🐛 FIX: Web - 동아리 가입신청서 버그 수정
  src/main/java/org/dongguk/jjoin/repository/AnswerRepository.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
Labels: 선호, FIX

#102 [REFACTOR] Web - 동아리 게시글 리팩토링
  src/main/java/org/dongguk/jjoin/repository/NoticeRepository.java
  src/main/java/org/dongguk/jjoin/service/ClubService.java
Labels: 재형, REFACTOR

#105 🐛 FIX : 동아리 타입에 연합동아리 추가
  src/main/java/org/dongguk/jjoin/domain/type/DependentType.java
Labels: 재형, FIX

#106 🐛 FIX: Web - 유저 정보 및 동아리 정보 수정 오류 해결
  src/main/java/org/dongguk/jjoin/domain/Club.java
  src/main/java/org/dongguk/jjoin/domain/User.java
  src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageUpdateDto.java
  src/main/java/org/dongguk/jjoin/service/ManagerService.java
  src/main/java/org/dongguk/jjoin/service/UserService.java
Labels: 선호, FIX

#108 🐛 FIX: Web - 유저 정보 및 동아리 정보 수정 오류 해결
  src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
Labels: 선호, FIX

#111 🐛 FIX: 동아리 검색 로직 수정
  src/main/java/org/dongguk/jjoin/service/SearchService.java
Labels: 재형, FIX
